name: 'Hall of Contributions'
description: 'Automatically updates your README with a list of your open source contributions'
inputs:
  github_token:
    description: 'GitHub token to use for fetching data from GitHub and updating the README'
    required: true
  configuration_file:
    description: 'Configuration file for the action'
    required: false
    default: '.github/hall-of-contributions/configuration.json'
runs:
  using: 'composite'
  steps:
    - name: Checkout repository
      uses: actions/checkout@v3  # Automatically checkout the repository
      with:
        repository: 'nick-w-nick/hall-of-contributions'  # Specify the repository to checkout
    
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'  # Specify Node.js version (adjust as necessary)
    
    - name: Install dependencies
      shell: bash
      run: npm install  # Install dependencies for your action (e.g., @actions/core)
    
    - name: Run custom image update logic
      shell: bash
      run: node dist/index.js  # Run the custom script to modify files like README.md
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}  # Pass the GitHub token as an environment variable
        CONFIGURATION_FILE: ${{ inputs.configuration_file }}  # Pass the configuration file as an environment variable
